### ISSUE TITLE
一对一填报=>院校章程点击无响应

### ISSUE THREAD

**Issue by Sevgilid** [Jonelsy/Vue_volunteer#1]
我看代码发现没绑定任意事件，在返回的列表数据里院校章程的url。原本的开发思路是直接跳转院校官网章程页码

**Comment by Jonelsy** [comment]
是的，你观察的很仔细，这是一个开发上的失误，只需要将数据绑定上即可，我会在今天晚上将bug修复

**Comment by Jonelsy** [comment]
我已经修复这个bug，请重新拉取下

**Comment by Sevgilid** [comment]
你最新更得代码好像又把这段逻辑覆盖回去了 
 <el-link type="primary"  :href="scope.row.AdmissionRegulationsURL" target="_blank" v-if="scope.row.AdmissionRegulationsURL!=null">点击查看</el-link>

**Comment by Jonelsy** [comment]
非常抱歉，我仔细的检查了我本地与仓库的代码，并没有发现上述问题，我觉得有可能是您在处理本地分支的过程中出现合并冲突您没有妥善处理，请重新拉取最新代码，以下是仓库中的代码
![Snipaste_2023-11-22_15-54-38](https://github.com/Jonelsy/Vue_volunteer/assets/113672133/85d28ddc-890c-46d0-acc7-b44cc8eea528)
