### ISSUE TITLE
学生管理：一对一方案制定新增学生后返回后数据展示失败

### ISSUE THREAD

**Issue by Sevgilid** [Jonelsy/Vue_volunteer#2]
性格测试列异常：学生管理 =》一对一方案制定新增学生后会返回会无法正常展示列表。将性格测试列注释后正常展示删除新增的学生后再取消注释可正常展示。

**Comment by Sevgilid** [comment]
我观察是因为新增的用户pic_major为null而非null.png。我没有找到更好的解决办法，最后采用判断scope.row.pic_major !== null来展示不同的el-image。然后内部图片设置为那张“暂无数据”图

**Comment by Jonelsy** [comment]
是的，我默认增加学生的时候传递pic_major是为null，预想传递，数据库会自动设置值为null.png，这样就实现了默认展示null.png的图片，您可以自己手动设置数据库student中pic_major默认值为null.png，后续我会查看并更新这个bug
