### ISSUE TITLE
关闭个性化推荐时搜索的大学对应学生展示如图所示，符合预期吗

### ISSUE THREAD

**Issue by Sevgilid** [Jonelsy/Vue_volunteer#3]
![image](https://github.com/Jonelsy/Vue_volunteer/assets/107530027/9e9ebcb6-9815-4fa1-9eef-072a37cc144d)

**Comment by Jonelsy** [comment]
是的，关闭推荐后只是把不推荐的院校全部展示出来，原本推荐院校的展示推荐依旧存在，因为推荐的逻辑是在前端根据每一行的最低录取排名和本人排名进行对比，低于一定百分比和高于一定百分比展示不同的推荐词

**Comment by Jonelsy** [comment]
所有问题都已解决，目前在个性化开启的时候不支持模糊查询，您可以试着解决一下，在后端文件student模块studnet.service.ts的getSchool方法中，有详细的注释您可以找到，希望您可以提供一些可用思路

**Comment by Sevgilid** [comment]
我的建议调整方案是进入方案制定页时：
1.个性化推荐默认关闭
（1）显示院校列表按院校代码或其他排序方式默认排序（非推荐排序方式）
（2）关闭时仍显示等效排名相关逻辑，保留等效排名差距过大不显示对应字样；支持模查询院校
2.个性化推荐开启时：
（1）使用推荐排序方式展示院校列表
（2）仍支持等效排名和模糊查询

**Comment by Jonelsy** [comment]
我明白您了您的意思，但是在后台逻辑中，开启个性化时的查询方法中，nestjs不支持多条件合并查询，对此在逻辑中我运用了大量的if...else....这样是及其不友好的代码。我会按照您的预期改进，但会经历比较长的周期，如果您有更好的代码优化层面的建议，欢迎与我分享

**Comment by Sevgilid** [comment]
我指的是关闭推荐排序方式时使用一种新的查询排序方式，可以先不考虑推荐的查询；不用考虑多条件合并查询

**Comment by Jonelsy** [comment]
感谢您的分享，但是我在原有代码上还是按照我原本思想尝试了以下，发现可以实现上述功能，就更新在了最新的提交中
