### ISSUE TITLE
学生管理-新增学生：成绩过低”==！

### ISSUE THREAD

**Issue by Sevgilid** [Jonelsy/Vue_volunteer#4]
![image](https://github.com/Jonelsy/Vue_volunteer/assets/107530027/3c69f4f1-f47a-4478-b90e-f5f1d14ada8b)
小bug：新增学生时输入670成功的msg提示为“成绩过低”==！
建议优化：提交成功后可以跳转学生管理页

**Comment by Jonelsy** [comment]
好的，我已知悉，最初后端设定的是分数过低导致没有对应排名的判断，没有想过高出650的判断，今晚我会修复这个bug,您的优化建议我会处理，一并在今晚commit

**Comment by Sevgilid** [comment]
拉去最新代码后添加学生按钮消失了
