### ISSUE TITLE
新增学生-前端校验及对message类型处理，后端状态码

### ISSUE THREAD

**Issue by Sevgilid** [Jonelsy/Vue_volunteer#5]
![image](https://github.com/Jonelsy/Vue_volunteer/assets/107530027/6316a0b2-88c3-46d6-a3c2-8fde62275728)
编辑分数是校验不能超过680吗。假设是这样，但添加学生虽然内容是显示不合法没有排名等，但显示的提示类型确实success即绿色的El-message类型（新增时不合校验并非和编辑情况相同而显示为success类型），且学生列表中添加成功了。个人认为正确的做法是将校验前端同样做校验change时触发体系，提交不了避免此情况。但后端仍需要返回不同的状态码，前端对非200（此项目中为0）时message改为error类型。
![image](https://github.com/Jonelsy/Vue_volunteer/assets/107530027/0c3efd00-ea41-484e-a4a6-86374516fcc6)

**Comment by Jonelsy** [comment]
非常感谢您的提示，我已经修复了这个问题，在前端增加了对分数的自定义校验，很抱歉这么迟更新这个问题，我目前正在北漂，你知道的，还没毕业的大学牲就是免费的劳动力，元旦快乐！我正在努力学习react等新技术，希望你也可以继续努力
