### ISSUE TITLE
学生管理->一对一方案制定

### ISSUE THREAD

**Issue by Sevgilid** [Jonelsy/Vue_volunteer#6]
![image](https://github.com/Jonelsy/Vue_volunteer/assets/107530027/fed9765d-0dc8-4558-89d7-b63c7542adbf)
![image](https://github.com/Jonelsy/Vue_volunteer/assets/107530027/d8709225-c7c9-4c0c-bf02-95ee2ee81bf8)
![image](https://github.com/Jonelsy/Vue_volunteer/assets/107530027/83d5b02c-f3b2-4858-b44e-4ca4c9f3e401)

点击第二页有数据，第一页控制台报错。我想应该是我在性格测试模块点击绑定学生时随便上传了一个md文件绑定导致。所以我的疑问是：（1）性格测试完成点击绑定学生时需要上传的文件是什么文件呢？（2）我随意上传文件显示成功但更新失败

**Comment by Jonelsy** [comment]
这确实是一个技术上的疏忽，在性格测试完成后可以保存测试截图到本地，然后可以允许绑定到某个学生上，即可在一对一填报界面中学生列表内显示这个图片，我并没有对这个上传做任何格式和大小的判断，导致了出现这个错误，我会在今晚修复这个问题
