### ISSUE TITLE
作者您好，请问项目背景中提到的“自2024年6月后，高考改革”，指的是什么改革？

### ISSUE THREAD

**Issue by WHIPLASHCZ** [Jonelsy/Vue_volunteer#7]
我没有在搜索引擎上查到有关2024年6月份内蒙古高考改革的有效信息，请问这个改革和本项目的主要功能高考志愿填报有什么冲突的地方？

**Comment by Jonelsy** [comment]
您好，关于内蒙古高考志愿改革信息，是从2022年高中选课由文理分科转为3+2选科模式，这就导致原本的实时志愿报考失效，进而推断出采用全国统一的平行志愿报考。
